# Makefile 
# ***************************************************************

PROGRAMS = \
    setArrayImp \
    setLinkedListImp\
   

# ***************************************************************
# Parameters to control Makefile operation
# Note that the gccx command script must be defined

#CC = gccx
#gcc 

CFLAGS = 

# ***************************************************************
# Entry to bring the package up to date

all: driver-array driver-list

# ***************************************************************
# Standard entries to remove files from the directories
#    tidy    -- eliminate unwanted files
#    scratch -- delete derived files in preparation for rebuild

tidy:
	rm -f ,* .,* *~ core a.out graphics.ps

scratch: tidy
	rm -f *.o *.a $(PROGRAMS)

# ***************************************************************
# C compilations

setArrayImp.o: setArrayImp.c set.h
	$(CC) $(CFLAGS) -c setArrayImp.c

setLinkedList.o: setLinkedListImp.c set.h
	$(CC) $(CFLAGS) -c setLinkedList.c

driver.o: driver.c set.h
	$(CC) $(CFLAGS) -c driver.c



# ***************************************************************
# Executable programs

driver-array: driver.o setArrayImp.o
	$(CC) $(CFLAGS) -o driver.o setLinkedListImp.o driver-array

driver-list: driver.o setLinkedListImp.o
	$(CC) $(CFLAGS) -o driver.o setLinkedListImp.o driver-list
